/**
 * 风格中英文映射表。
 * 下拉显示中文 label,提交时用英文 name(后端 art_styles.json 的 key)。
 * 未列出的风格回退用英文原名。
 */
export const styleLabels: Record<string, string> = {
  None: "无风格",
  "Painted Anime": "绘画风动漫",
  "Casual Photo": "日常照片",
  Cinematic: "电影感",
  "Digital Painting": "数字绘画",
  "Concept Art": "概念艺术",
  "3D Disney Character": "3D 迪士尼角色",
  "2D Disney Character": "2D 迪士尼角色",
  "Disney Sketch": "迪士尼素描",
  "Concept Sketch": "概念素描",
  Painterly: "绘画质感",
  "Oil Painting": "油画",
  "Oil Painting - Realism": "油画 - 写实",
  "Oil Painting - Old": "油画 - 古典",
  "Oil Painting - 70s Pulp": "油画 - 70年代复古",
  "Professional Photo": "专业摄影",
  Anime: "动漫",
  "Drawn Anime": "手绘动漫",
  "Anime Screencap": "动漫截图",
  "Cute Anime": "可爱动漫",
  "Soft Anime": "柔和动漫",
  "Fantasy Painting": "奇幻绘画",
  "Fantasy Landscape": "奇幻风景",
  "Fantasy Portrait": "奇幻肖像",
  "Studio Ghibli": "吉卜力工作室",
  "50s Enamel Sign": "50年代搪瓷标牌",
  "Vintage Comic": "复古漫画",
  "Franco-Belgian Comic": "法比漫画",
  "Tintin Comic": "丁丁历险记",
  Medieval: "中世纪",
  "Pixel Art": "像素艺术",
  "Furry - Oil": "兽人 - 油画",
  "Furry - Cinematic": "兽人 - 电影感",
  "Furry - Painted": "兽人 - 绘画",
  "Furry - Drawn": "兽人 - 手绘",
  "Cute Figurine": "可爱手办",
  "3D Emoji": "3D 表情",
  Illustration: "插画",
  "Cute Illustration": "可爱插画",
  "Flat Illustration": "扁平插画",
  Watercolor: "水彩",
  "1990s Photo": "90年代照片",
  "1980s Photo": "80年代照片",
  "1970s Photo": "70年代照片",
  "1960s Photo": "60年代照片",
  "1950s Photo": "50年代照片",
  "1940s Photo": "40年代照片",
  "1930s Photo": "30年代照片",
  "1920s Photo": "20年代照片",
  "Vintage Pulp Art": "复古 pulp 艺术",
  "50s Infomercial Anime": "50年代广告动漫",
  "3D Pokemon": "3D 宝可梦",
  "Painted Pokemon": "绘画宝可梦",
  "2D Pokemon": "2D 宝可梦",
  "Vintage Anime": "复古动漫",
  "Neon Vintage Anime": "霓虹复古动漫",
  Manga: "漫画",
  "Fantasy World Map": "奇幻世界地图",
  "Fantasy City Map": "奇幻城市地图",
  "Old World Map": "古世界地图",
  "3D Isometric Icon": "3D 等距图标",
  "Flat Style Icon": "扁平风格图标",
  "Flat Style Logo": "扁平风格 Logo",
  "Game Art Icon": "游戏艺术图标",
  "Digital Painting Icon": "数字绘画图标",
  "Concept Art Icon": "概念艺术图标",
  "Cute 3D Icon": "可爱 3D 图标",
  "Cute 3D Icon 𝗦𝗲𝘁": "可爱 3D 图标组",
  "Crayon Drawing": "蜡笔画",
  Pencil: "铅笔素描",
  "Tattoo Design": "纹身设计",
  Waifu: "二次元老婆",
  "YuGiOh Art": "游戏王卡牌",
  "Traditional Japanese": "日本传统",
  "Nihonga Painting": "日本画",
  Claymation: "黏土动画",
  Cartoon: "卡通",
  "Cursed Photo": "诡异照片",
};

/** 获取风格的中文显示名,无映射时回退英文原名。 */
export function styleLabel(name: string): string {
  return styleLabels[name] ?? name;
}
